version: '3.8'
services:
  python_bench:
    env_file: ../.env
    image: python-bench:${USER}
    container_name: python_bench
    volumes:
      # Mount full host home directory
      - ~:/home/${USER}:cached
      - ../..:/workspace:cached
    ports:
      - "8000:8000"
      - "8888:8888"
    command: sleep infinity
    working_dir: /workspace
volumes: {}
