services:
  workspace:
    image: cloud-bench:brett
    command: sleep infinity
    volumes:
      # Mount full host home directory
      - ~:/home/brett:cached
      - .:/workspace
    working_dir: /workspace
    environment:
      - USER=brett
    network_mode: host
